### ISSUE TITLE
Muk Backend Theme Error - v17 CE

### ISSUE THREAD

**Issue by GesangPJ** [muk-it/odoo-modules#1]
Steps :
1. Change all color in settings, except app text and background color
2. Change background  image
3. Save
4. It works / normal
5. Change primary and brand color again (2nd time)
6. Save
7. Error

Untill now i cant solve the error, restarting the server also not solving it, probably i need to reinstall odoo server because now the server is Error 500 after restart, i cant access the front web and backend, below is the log : 

Error Log : 
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 99, in lookup
    r = d[key]
  File "<decorator-gen-5>", line 2, in __getitem__
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.qweb', <function IrQWeb._generate_asset_links_cache at 0x7f48f924cd30>, 'web.assets_web', True, True, (('website_id', False),), False)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 99, in lookup
    r = d[key]
  File "<decorator-gen-5>", line 2, in __getitem__
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.asset', <function IrAsset._get_asset_paths at 0x7f48f9be9750>, 'web.assets_web', (('website_id', False),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<190>", line 160, in template_190
  File "<190>", line 142, in template_190_content
  File "<190>", line 103, in template_190_t_call_0
  File "<190>", line 55, in template_190_t_set_2
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 2461, in _get_asset_nodes
    links = self._get_asset_links(bundle, css=css, js=js, debug=debug)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 2476, in _get_asset_links
    return self._generate_asset_links_cache(bundle, css=css, js=js, assets_params=assets_params, rtl=rtl)
  File "<decorator-gen-70>", line 2, in _generate_asset_links_cache
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 104, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 2530, in _generate_asset_links_cache
    return self._generate_asset_links(bundle, css, js, False, assets_params, rtl)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 2606, in _generate_asset_links
    asset_bundle = self._get_asset_bundle(bundle, css=css, js=js, debug_assets=debug_assets, rtl=rtl, assets_params=assets_params)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 2553, in _get_asset_bundle
    files, external_assets = self._get_asset_content(bundle_name, assets_params)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 2535, in _get_asset_content
    asset_paths = self.env['ir.asset']._get_asset_paths(bundle=bundle, assets_params=assets_params)
  File "<decorator-gen-52>", line 2, in _get_asset_paths
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 104, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_asset.py", line 154, in _get_asset_paths
    self._fill_asset_paths(bundle, asset_paths, [], addons, installed, **assets_params)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_asset.py", line 187, in _fill_asset_paths
    self._process_path(bundle, directive, target, path_def, asset_paths, seen, addons, installed, bundle_start_index, **assets_params)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_asset.py", line 208, in _process_path
    self._fill_asset_paths(path_def, asset_paths, seen + [bundle], addons, installed, **assets_params)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_asset.py", line 187, in _fill_asset_paths
    self._process_path(bundle, directive, target, path_def, asset_paths, seen, addons, installed, bundle_start_index, **assets_params)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_asset.py", line 208, in _process_path
    self._fill_asset_paths(path_def, asset_paths, seen + [bundle], addons, installed, **assets_params)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_asset.py", line 187, in _fill_asset_paths
    self._process_path(bundle, directive, target, path_def, asset_paths, seen, addons, installed, bundle_start_index, **assets_params)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_asset.py", line 208, in _process_path
    self._fill_asset_paths(path_def, asset_paths, seen + [bundle], addons, installed, **assets_params)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_asset.py", line 191, in _fill_asset_paths
    self._process_path(bundle, asset.directive, asset.target, asset.path, asset_paths, seen, addons, installed, bundle_start_index, **assets_params)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_asset.py", line 223, in _process_path
    target_index = asset_paths.index(target, bundle)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_asset.py", line 398, in index
    self._raise_not_found(path, bundle)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_asset.py", line 431, in _raise_not_found
    raise ValueError("File(s) %s not found in bundle %s" % (path, bundle))
ValueError: File(s) /muk_web_colors/static/src/scss/colors_light.scss not found in bundle web._assets_primary_variables

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2157, in __call__
    response = request._serve_db()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1732, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1759, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1873, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 209, in _dispatch
    result.flatten()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1248, in flatten
    self.response.append(self.render())
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1240, in render
    return request.env["ir.ui.view"]._render_template(self.template, self.qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 443, in _render_template
    return super()._render_template(template, values=values)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 2044, in _render_template
    return self.env['ir.qweb']._render(template, values)
  File "/usr/lib/python3/dist-packages/odoo/tools/profiler.py", line 292, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 593, in _render
    result = ''.join(rendering)
  File "<190>", line 166, in template_190
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
ValueError: File(s) /muk_web_colors/static/src/scss/colors_light.scss not found in bundle web._assets_primary_variables
Template: web.webclient_bootstrap
Path: /t/t/t[1]/t[2]/t
Node: <t t-call-assets="web.assets_web"/>
```

**Comment by GesangPJ** [comment]
I forgot something, i also change company logo and favicon, i change it when change brand color & primary color at second time.

**Comment by keshrath** [comment]
Hello, this is already a known issue and should be fixed with the newest version. Can you confirm this? It might be necessary to uninstall the theme and install it again.

**Comment by GesangPJ** [comment]
So far isn't error after i change all colors, background, and icons, thanks.

**Comment by mr-contreras** [comment]
how did you solve it? @GesangPJ

**Comment by GesangPJ** [comment]
@mr-contreras after i re-install odoo 17 and install the theme again, i remove my browser cache then start odoo and change the theme colors, background, logo, and it works, even change for the 3rd time it didn't cause any errors. Make sure you install the latest version of the theme. And one more is you open the module first and then click install, untill now some addons cause odoo to crash if you directly click install in addons list.

**Comment by Kaliuta** [comment]
He also repeated this mistake. Here are the steps:
1. Change the brand color.
2. Save.
3. Change the brand color again (second time).
4. Save.
5. Result: Error.

The error occurs if the website module is installed.
Everything works fine without the website module installed.

I understood that it is related to the method:

def _get_custom_attachment(self, custom_url, op='=')

which is located in the path: /addons/website/models/assets.py

If the override of this method is commented out, there will be no error.

This requires additional research, but I think the problem is that the attachment is filtered by website_id, and style attachments generated by this module may not have this field, which leads to an error.
