### ISSUE TITLE
Chatter error

### ISSUE THREAD

**Issue by LucianVoju** [muk-it/odoo-modules#11]
Hello and thanks for this nice modules.
I have a chatter error. 
How to reproduce: 

- install muk_web_chatter
- go to settings and click Activate the developer mode

I also got a similar error  in email marketing app/ new mailing/ select a template and change a color the design editor

<img width="1713" alt="Screenshot 2024-09-25 at 16 52 19" src="https://github.com/user-attachments/assets/076253ec-43fe-46f5-b2b6-b8df990ab3ab">

`UncaughtPromiseError > OwlError
Uncaught Promise > Invalid props for component 'Thread': 'showTrackingMessages' is missing
OwlError: Invalid props for component 'Thread': 'showTrackingMessages' is missing
    Error: Invalid props for component 'Thread': 'showTrackingMessages' is missing
        at Object.validateProps (http://localhost:10017/web/assets/feb5609/web.assets_web.min.js:1142:67)
        at Discuss.template (eval at compile (http://localhost:10017/web/assets/feb5609/web.assets_web.min.js:1503:374), <anonymous>:136:15)
        at Fiber._render (http://localhost:10017/web/assets/feb5609/web.assets_web.min.js:940:96)
        at Fiber.render (http://localhost:10017/web/assets/feb5609/web.assets_web.min.js:939:6)
        at ComponentNode.initiateRender (http://localhost:10017/web/assets/feb5609/web.assets_web.min.js:1007:47)`

**Comment by keshrath** [comment]
Hello, I am currently unable to reproduce the error. You can try to define the assets in the manifest and check whether this fixes the error.

**Comment by keshrath** [comment]
https://github.com/muk-it/odoo-modules/commit/5170aa9e70dea28129d61d1f9a8cbb13d4f6537f
