### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by lo2ay89** [muk-it/odoo-modules#8]
As soon as I install the module.zip i get internal server error with the following odoo log:

2024-06-11 11:54:53,738 13996 ERROR odoo24 odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "<190>", line 172, in template_190
  File "<190>", line 154, in template_190_content
  File "<190>", line 140, in template_190_t_call_0
AttributeError: 'res.users' object has no attribute 'sidebar_type'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Odoo 17.0.20231130\server\odoo\http.py", line 2157, in __call__
    response = request._serve_db()
  File "C:\Program Files\Odoo 17.0.20231130\server\odoo\http.py", line 1732, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "C:\Program Files\Odoo 17.0.20231130\server\odoo\service\model.py", line 133, in retrying
    result = func()
  File "C:\Program Files\Odoo 17.0.20231130\server\odoo\http.py", line 1759, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "C:\Program Files\Odoo 17.0.20231130\server\odoo\http.py", line 1873, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "C:\Program Files\Odoo 17.0.20231130\server\odoo\addons\website\models\ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "C:\Program Files\Odoo 17.0.20231130\server\odoo\addons\base\models\ir_http.py", line 209, in _dispatch
    result.flatten()
  File "C:\Program Files\Odoo 17.0.20231130\server\odoo\http.py", line 1248, in flatten
    self.response.append(self.render())
  File "C:\Program Files\Odoo 17.0.20231130\server\odoo\http.py", line 1240, in render
    return request.env["ir.ui.view"]._render_template(self.template, self.qcontext)
  File "C:\Program Files\Odoo 17.0.20231130\server\odoo\addons\website\models\ir_ui_view.py", line 443, in _render_template
    return super()._render_template(template, values=values)
  File "C:\Program Files\Odoo 17.0.20231130\server\odoo\addons\base\models\ir_ui_view.py", line 2044, in _render_template
    return self.env['ir.qweb']._render(template, values)
  File "C:\Program Files\Odoo 17.0.20231130\server\odoo\tools\profiler.py", line 292, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "C:\Program Files\Odoo 17.0.20231130\server\odoo\addons\base\models\ir_qweb.py", line 593, in _render
    result = ''.join(rendering)
  File "<190>", line 178, in template_190
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
AttributeError: 'res.users' object has no attribute 'sidebar_type'
Template: web.webclient_bootstrap
Path: /t/t/t[5]
Node: <t t-set="body_classname" t-value="\'%s %s\' % (body_classname, body_sidebar_classname)"/>

**Comment by keshrath** [comment]
sounds to me as if the module has not been completely installed. update muk_web_appsbar via the Odoo shell.
